# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pradeep K. Pant Blog
email: pp@pradeeppant.com
url: https://pradeeppant.com
description: >- 
  My notes on Software Engineering, Data Science,
  AI/ML, Process Mining, Research and Technology in general
baseurl: ""
#baseurl: "/categories/" 
#baseurl: "" # the subpath of your site, e.g. /blog
#url: http://pradeeppant.com
#url: "http://ppantdev:80" # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://192.168.1.100" # the base hostname & protocol for your site, e.g. http://example.com
#url: "0.0.0.0" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ppant
# github_username:  ppant
# linkedin_username: ppant 
# Build settings
#theme: jekyll-theme-minimal
#theme: minima
skin: sunrise
paginate: 20
paginate_path: "/blog/page:num/"
#show_excerpts: true
disqus:
    shortname: ppant
#theme: Emerald
#theme: jekyll-theme-hacker
#social_links:
#    twitter: ppant
#    github:  ppant
#    rss: rss
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
 # - jekyll-gist
  - jekyll-paginate  
  - jekyll-archives
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: UA-15272551-6
permalink: /:categories/:title/



# Custom vars
# version: 3.0.0
# sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # # page. If you change your paginate_path,
                                # # set this to the root of the paginate_path
                                # # to enable a separate blog link.
# mailchimp : true
# mailchimp_list_name : Pradeep Pant's Newsletter
# mailchimp_list_why : What's in it for them?
# mailchimp_embed_action : http://jigyasu.us13.list-manage.com/subscribe/post?u=5bc4802fda0082620b6b67d5e&amp;id=f825c6567a

# timezone:    Asia/Calcutta
# locale:      en_US
# future:      true

# Specify the author for blog posts
# author:
  # name: 'Pradeep Pant'
  # email: 'pp[at]pradeeppant[dot]com'
  # github: ppant
  # instagram: pradeepkpant
  # instagram_url: www.instagram.com/pradeepkpant
  # linkedin: ppant
  # disqus_shortname: ppant
  # google_analytics_id: 
  # google_analytics_url: 
  # bio: Techie, Fitness enthusiast
jekyll-archives:
  enabled: all
  layouts:
    year: archive/year
    month: archive/month
    day: archive/day
    tag: archive/tag
    category: archive/category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/category/:name/'
