title: Pradeep K. Pant Blog
email: pp@pradeeppant.com
url: https://pradeeppant.com
description: >- 
  My notes on Computers, technology, travel  and fitness
baseurl: ""
skin: sunrise
paginate: 20
paginate_path: "/blog/page:num/"
disqus:
    shortname: ppant
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jemoji
google_analytics: UA-15272551-6
permalink: /:year/:month/:day/:title/
author:
  name: 'Pradeep K. Pant'
  email: 'pp@pradeeppant.com'
include:
  - _category
  - data
jekyll-archives:
  enabled:
    - tags
    - year
    - month
    - day
  layouts:
    year: archive/year
    month: archive/month
    day: archive/day
    tag: archive/tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'
category_titles:
  tech: Software Engineering
  software: Software Engineering
  ai-ml: AI/ML
  process-mining: Process Mining
  fitness: Fitness
  running: Running
  cycling: Cycling
  health: Health
  travel: Travel
  life: Life
  community: Community
